spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${whiz.datasource.ip}:3306/whiz_oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${whiz.datasource.username}
    password: ${whiz.datasource.password}