iot-service-type: ${IOT_SERVICE_TYPE:all}

spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${whiz.datasource.ip}:3306/whiz_base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: ${whiz.datasource.username}
#    password: ${whiz.datasource.password}

  profiles:
    active: ${ACTIVE:cn.dev}

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: iot
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          # 重试次数
          max-attempts: 5
          # 重试最大间隔时间
          max-interval: 20000
          # 重试初始间隔时间
          initial-interval: 4000
          # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
      channel:
        size: 200
        checkout-timeout: 100

  rbtRabbitmq:
    enable: true
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: iot
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          # 重试次数
          max-attempts: 5
          # 重试最大间隔时间
          max-interval: 20000
          # 重试初始间隔时间
          initial-interval: 4000
          # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
      channel:
        size: 200
        checkout-timeout: 100


  mqtt:
    enable: true
    qos: 0
    retained: false
    username: admin
    password: public
    completionTimeout: 3000
    # mqtt连接tcp地址
    host-url: tcp://127.0.0.1:1883
    # 客户端Id，每个启动的id要不同
    client-id: IOT-ICER
    # 默认主题
    default-topic: test
    subscribeTopics:
      - /icer/#
      - $SYS/brokers/+/clients/+/connected
      - $SYS/brokers/+/clients/+/disconnected
       # 状态数据
      - /thing/status/+/+/post
      - /thing/event/+/+/post
      - /thing/online/+/+/post
    timeout: 300
    keepalive: 300

  rbtmqtt:
    enable: true
    qos: 0
    retained: false
    username: admin
    password: public
    completionTimeout: 3000
    # mqtt连接tcp地址
    host-url: tcp://127.0.0.1:1883
    # 客户端Id，每个启动的id要不同
    client-id: IOT-RBT
    # 默认主题
    default-topic: test
    subscribeTopics:
      - /rbt/#
    timeout: 300
    keepalive: 300

ice:
  active: cn.dev

feign:
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒

