spring:
  cloud:
    nacos:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
    gateway:
      routes:
        - id: goods
          uri: lb://whiz-goods
          predicates:
            - Path=/api-goods/**
          filters:
            - StripPrefix= 1

whiz:
  oauth2:
    token:
      store:
        type: authJwt
  security:
    ignore:
      # 忽略认证的url地址
      httpUrls: >
        /api-oauth/oauth/**,
        /api-oauth/validata/**,
        /api-oauth/css/**,
        /api-oauth/images/**,
        /api-oauth/js/**,
        /login.html,
        /user/login,
        /api-oauth/tokens/key
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
          - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
          - webApp
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true
#  loadbalance:
#    version: test
#    isolation:
#      enabled: true
#      chooser: com.damon.common.lb.chooser.impl.RoundRuleChooser