spring:
  cloud:
    nacos:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
    gateway:
      routes:
        - id: goods
          uri: lb://whiz-goods
          predicates:
            - Path=/api-goods/**
          filters:
            - StripPrefix= 1

whiz:
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true
