spring:
  cloud:
    nacos:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
    gateway:
      routes:
        - id: base
          uri: lb://whiz-base
          predicates:
            - Path=/api-base/**
          filters:
            - StripPrefix=1

        - id: auth
          uri: lb://whiz-oauth
          predicates:
            - Path=/api-oauth/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: auth-login-authorize
          uri: lb://whiz-oauth
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader

        - id: auth-login-page
          uri: lb://whiz-oauth
          predicates:
            - Path=/login.html
          filters:
            - PreserveHostHeader

        - id: auth-login-process
          uri: lb://whiz-oauth
          predicates:
            - Path=/user/login
          filters:
            - PreserveHostHeader

        - id: auth-login-token
          uri: lb://whiz-oauth
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader

        - id: auth-check-process
          uri: lb://whiz-oauth
          predicates:
            - Path=/oauth/check_token
          filters:
            - PreserveHostHeader

whiz:
  oauth2:
    token:
      store:
        type: authJwt
  security:
    ignore:
      # 忽略认证的url地址
      httpUrls: >
        /api-oauth/oauth/**,
        /api-oauth/validata/**,
        /api-oauth/css/**,
        /api-oauth/images/**,
        /api-oauth/js/**,
        /login.html,
        /user/login,
        /api-oauth/tokens/key
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-base/menus/current,
          /api-base/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
          - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
          - webApp
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true
#  loadbalance:
#    version: test
#    isolation:
#      enabled: true
#      chooser: com.damon.common.lb.chooser.impl.RoundRuleChooser