spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${whiz.datasource.ip}:3306/whiz_base?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${whiz.datasource.username}
    password: ${whiz.datasource.password}


feign:
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒