spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${whiz.datasource.ip}:3306/whiz_file?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${whiz.datasource.username}
    password: ${whiz.datasource.password}

whiz:
  file:
    type: s3
    s3:
      type: aliYun
      accessKeyId: xxx
      accessKeySecret: xxx
      endpoint: xxx
      bucketName: xxx
      policyExpire: 3000
      callback: xxx
      maxSize: 500
      dirPrefix: mall/dev/




